### ISSUE TITLE
Supporting v2 API

### ISSUE THREAD

**Issue by wonderlandpark** [koreanbots/js-sdk#18]
# Should support v2 API before v2 release.

### BaseURL
Beta(For now):

```
beta.koreanbots.dev/api
```

Production
```
koreanbots.dev/api
```

### Document

https://github.com/koreanbots/api-docs

## To-do

- [x] Get User
- [x] Get Bot
- [x] Widget
- [x] Update Server

**Comment by zero734kr** [comment]
I’m too lazy to develop

**Comment by wonderlandpark** [comment]
> I’m too lazy to develop

Fired

**Comment by wonderlandpark** [comment]
This issue is due to `2020-11-1`

**Comment by zero734kr** [comment]
I already terminated my job and please reopen this issue when js-sdk needs some more features.

**Comment by wonderlandpark** [comment]
Reopening as the v2 is being re-written

**Comment by zero734kr** [comment]
Where is the documentation about the API and its routes?

**Comment by wonderlandpark** [comment]
Not yet

**Comment by zero734kr** [comment]
I hope that not have much to edit, you decided to rewrite just AFTER I finalized the API SDK

**Comment by wonderlandpark** [comment]
<kbd>X</kbd>

**Comment by zero734kr** [comment]
When the API documents are ready, I'll start working

**Comment by wonderlandpark** [comment]
K

**Comment by zero734kr** [comment]
K? What do you mean?

**Comment by zero734kr** [comment]
Any updates in API? @wonderlandpark

**Comment by wonderlandpark** [comment]
Not yet

**Comment by wonderlandpark** [comment]
@zero734kr Added Docs
