### ISSUE TITLE
[BUG] Mybot: API requests keep occurring without cache every time a Mybot instance is constructed

### ISSUE THREAD

**Issue by kms0219kms** [koreanbots/js-sdk#197]
## SDK Version information
* koreanbots@3.2.1 installed with pnpm.

## Problem
https://github.com/koreanbots/js-sdk/blob/dbe9ca876e7faa305010cbb7412fbc99a9ed72d9/src/managers/Mybot.ts#L24-L39
According to this code (especially L35), when the MyBot class is created by the `new KoreanBots()` constructor, it makes a request to the API every time without caching, which may result in a rate limit error or IP blocking.

In particular, when running the KoreanBots SDK on each shard for purposes such as guild number synchronisation, a request to the API occurred every time a shard was created.

In fact, due to this behavior, a large number of requests were generated from "Machobot", a large-scale Discord bot that I run (approximately 14 shards), and a Cloudflare IP Ban occurred, so I would like to request improvement in this area (see the `Solutions suggestion` section below).

## Solutions suggestion
* Add cache with this `GET` method if it seriously needs to be called every time a `Mybot` class is constructed.
* If this GET method doesn't need to be called every time, improve it so that it doesn't send the request unless explicitly called the `fetch` method.

**Comment by skinmaker1345** [comment]
샤딩을 어떻게 진행하셨고, SDK를 어떻게 사용하셨는지 첨부 부탁드립니다.

**Comment by kms0219kms** [comment]
Discord.js의 ShardingManager를 통하여 샤딩하였고, 샤딩 된 후 koreanbots.mybot.update를 통하여 서버수를 업데이트 하도록 Util 클래스를 따로 빼어 사용하고 있었습니다.

**Comment by kms0219kms** [comment]
utils/kdl.ts
```ts
const koreanbots = new Koreanbots({
  api: {
    token: KB_TOKEN,
  },
  clientID: KB_CLIENTID,
});

// 한디리 서버 업데이트
export const KDLupdate = (
  serverSize: number,
  shardCount: number | undefined,
) => {
  koreanbots.mybot
    .update({ servers: serverSize, shards: shardCount })
    .then((res) =>
      console.log(
        "서버 수를 정상적으로 업데이트하였어요!\n반환된 정보:" +
          JSON.stringify(res),
      ),
    )
    .catch(console.error);
};
```

run.ts
```ts
import { ShardingManager } from "discord.js";
import { KDLupdate } from "./utils/kdl";

const manager = new ShardingManager("<번들된 봇 파일 경로>", {
  token: process.env.TOKEN,
});

manager.spawn().then((shards) => {
  setInterval(
    async () => {
      const guildCnt = await manager
        .broadcastEval((client) => client.guilds.cache.size)
        .then((r) =>
          r.reduce((acc: number, guildCount: number) => acc + guildCount, 0)
        );

      KDLupdate(guildCnt, shards.size);
    },
    10 * 60 * 1000
  );
});
```

이때 샤드가 발생할 때 마다 KDLupdate 실행을 위해 Koreanbots 클래스가 Construct되고, 요청이 대량 발송이 된 것으로 추측하고 있습니다. (서버수 동기화 외에는 sdk 사용중이 아님)

**Comment by kms0219kms** [comment]
run.ts
```ts
import { ShardingManager } from "discord.js";
import { KDLupdate } from "./utils/kdl";

const manager = new ShardingManager("<번들된 봇 파일 경로>", {
  token: process.env.TOKEN,
});

manager.spawn().then((shards) => {
  setInterval(
    async () => {
      const guildCnt = await manager
        .broadcastEval((client) => client.guilds.cache.size)
        .then((r) =>
          r.reduce((acc: number, guildCount: number) => acc + guildCount, 0)
        );

      KDLupdate(guildCnt, shards.size);
    },
    10 * 60 * 1000
  );
});
```

**Comment by kms0219kms** [comment]
이때 샤드가 발생할 때 마다 KDLupdate 실행을 위해 Koreanbots 클래스가 Construct되고, 요청이 대량 발송이 된 것으로 추측하고 있습니다. (서버수 동기화 외에는 sdk 사용중이 아님)

**Comment by skinmaker1345** [comment]
해당 파일이 어디서 또 임포트되었는지는 모르겠으나, 샤딩매니저가 아닌 봇 인스턴스(Client)와 함께 Koreanbots가 인스턴스화 되는 경우는 SDK의 고려 사항이 아닙니다. 말씀주신 증상으로 미뤄 보아 샤딩매니저가 자식 프로세스를 생성함과 동시에 SDK가 같이 초기화 되는 것으로 보이며, 이 경우 캐시는 근본적으로 해결법이 되지 못합니다.

**Comment by kms0219kms** [comment]
해당 파일은 이후 API를 직접 요청하여 사용자가 하트를 눌렀는지 체크하는 hasVoted 메소드를 위해 임포트 되는 케이스가 존재하나, 이것 또한 저희가 기대하던 behavior가 아닙니다.

현재는 해당 koreanbots 인스턴스를 run.ts애서 생성하고, 그 인스턴스를 props로 서버수 동기화 시 내려주는 것으로 임시방편을 만들어 두었습니다.

아직 해당 문제가 발생한지 얼마 지나지 않아, 원인을 완벽히 파악하진 못한 점 참고 부탁드리며, 말씀주신 내용이 원인인지 내부적으로 다시 점검해보겠습니다. 말씀주신 내용이 맞다면 캐싱은 따로 별다른 효과는 없는게 맞을 것 같네요.

**Comment by kms0219kms** [comment]
아직 해당 문제가 발생한지 얼마 지나지 않아, 원인을 완벽히 파악하진 못한 점 참고 부탁드리며, 말씀주신 내용이 원인인지 내부적으로 다시 점검해보겠습니다. 말씀주신 내용이 맞다면 캐싱은 따로 별다른 효과는 없는게 맞을 것 같네요.

**Comment by skinmaker1345** [comment]
샤딩 매니저의 동작 방식을 간단히 설명드리면, 샤딩매니저가 포함된 파일이 먼저 부모 프로세스로서 실행이 되고, 지정한 봇 실행 파일은 자식 프로세스로 실행이 됩니다. 즉 각 프로세스는 독립적인 Node.js 런타임이기에, 메모리 또한 공유되지 않습니다.
즉 hasVoted 만 사용하신다 할 지라도, 각 자식 프로세스는 각자의 SDK 인스턴스를 가지게 됩니다.

**Comment by skinmaker1345** [comment]
때문에 현재 SDK는 샤딩매니저가 아닌 내부 샤딩일 경우에만 제대로 사용이 가능하도록 설계되었습니다.
결론적으로 SDK의 버그로 보이지는 않으며, 직접 HTTP 요청을 하는 것이 옳아 보입니다.

**Comment by kms0219kms** [comment]
SDK의 설계 구조에 대해서 이해하지 못하고 있었네요. 샤딩매니저에서는 제대로 사용이 불가능하다는 점, 이해하였습니다.
직접 Axios를 통하여 HTTP 요청을 하도록, 개선토록 하겠습니다.
