### ISSUE TITLE
Import using paths

### ISSUE THREAD

**Issue by wonderlandpark** [koreanbots/js-sdk#43]
Use typescript config `paths`.

```json
"paths" : {
  "@util/*": ["src/util/*"]
}

Like this

**Comment by wonderlandpark** [comment]
Good Luck

**Comment by zero734kr** [comment]
https://github.com/microsoft/TypeScript/issues/10866

**Comment by zero734kr** [comment]
Looks like it's impossible when you use it for backend. I considered using some libs like ts-module-paths but it can only be used in development

**Comment by zero734kr** [comment]
Here is a quote from microsoft/TypeScript#10866:
> "paths" is designed **for use with loaders that allow remapping,** unlike the Node.js require().

**Comment by zero734kr** [comment]
You may not have known this because you only used "paths" option with TypeScript in next.js  projects that supports path remapping via webpack
