### ISSUE TITLE
오류 내용을 영어도 추가해줬으면

### ISSUE THREAD

**Issue by MoartMedia** [koreanbots/js-sdk#5]
![image](https://user-images.githubusercontent.com/18746638/81767036-697d7100-9512-11ea-9ff0-d225dcfaebb5.png)
뭐 그냥 요청 사항이긴한데 오류가 한글이라 영문만 지원하는 터미널에선 깨진답니다 ㅠㅠ..
영어도 추가해줬으면 좋겠네요.

**Comment by kijk2869** [comment]
sdk의 문제가 아닙니다, koreanbots API 자체에서 돌아오는 메시지가 한글입니다.
