### ISSUE TITLE
오타

### ISSUE THREAD

**Issue by vendettadelsangue** [koreanbots/js-sdk#7]
Bot.js 114번줄 버젼 오타 수정 부탁드립니다

**Comment by zero734kr** [comment]
2144952fc87c57cff402e000771ae91ba4754e1d 커밋에서 수정되었으며 추후 버전업때 1.1.2와 함께 수정될 예정입니다. 이슈 생성에 감사드리며 또 하고 싶으신 얘기가 있으시다면 이 이슈를 재오픈 부탁드립니다.
