### ISSUE TITLE
Discord.js v13 업데이트 필요

### ISSUE THREAD

**Issue by MadeGOD** [koreanbots/js-sdk#93]
v13 버전으로 업데이트 할시 기존 koreanbots 이 작동이 안됩니다. 해결해주시기 바랍니다.

**Comment by zero734kr** [comment]
구체적으로 오류가 발생해서 작동이 안 되는지, 이 경우 오류를 알려주시고, 다른 요인으로 인해 작동이 안 되는지 알려주시길 바랍니다.
