### ISSUE TITLE
v3 migration link not working

### ISSUE THREAD

**Issue by Jam-Manbo** [koreanbots/js-sdk#96]
## 잘못된 링크
* * *
> koreanbots js sdk의 [v2 -> v3 마이그레이션 가이드](https://github.com/koreanbots/js-sdk#v2---v3-%EB%A7%88%EC%9D%B4%EA%B7%B8%EB%A0%88%EC%9D%B4%EC%85%98-%EA%B0%80%EC%9D%B4%EB%93%9C)의 [링크](https://github.com/koreanbots/js-sdk/blob/master/docs/v3-migration.md)가 작동하지 않습니다

## 예상되는 정상적인 동작
* * *
> 링크가 작동해야 합니다

## 버전
* * *
> koreanbots sdk: v3.0.0

**Comment by zero734kr** [comment]
해당 가이드는 Koreanbots의 API가 갈아엎히기 전의 가이드라 실효성이 없어 삭제 되었습니다. README에서도 삭제 조치 하겠습니다.

**Comment by zero734kr** [comment]
v3 SDK의 문서는 [릴리즈](https://github.com/koreanbots/js-sdk/releases/tag/3.0.0) 페이지에 있는 링크들을 확인 해주세요.
